language: php
sudo: required

services:
  - docker

php:
  - '7.1'

env:
  global:
    - SERVICE_NAME=unbherbarium.lib.unb.ca
    - DOCKER_UPSTREAM_IMAGE=unblibraries/drupal:alpine-nginx-php7-8.x-composer
    - DEPLOY_BRANCHES=dev,prod
    - OLD_IMAGES_TO_KEEP=2
    - AMAZON_ECR_REGION=us-east-1

before_install:
  - git clone -b 8.x-1.x git://github.com/unb-libraries/travis-kube-deploy-drupal.git travis
  - travis/installDockerCompose.sh

before_script:
  - travis/setComposePort.sh
  - travis/setDockerComposeEnv.sh
  - travis/buildInstanceForTesting.sh
  - travis/waitForDeploy.sh
  - travis/checkStartupForErrors.sh

script:
  - travis/testInstance.sh

after_success:
  - travis/installAuthAws.sh
  - travis/buildInstanceTheme.sh
  - travis/buildImagePushToRepo.sh
  - travis/cleanupOldImages.sh
  - travis/triggerKubeDeploy.sh

notifications:
  slack:
    secure: 2+pDK2zzUbYunA3/pOtLaFHgVShAsY1co+0FMxHS/SMgUze08lARM/1JGflqDWNOzcVtsG6QIkk7ZMR2dHjwH4G/sKkSIvN7Y3ftp+QFB1arfFfog+0tbZRB1Zy0sby1/wbbnXRs/z0bAaiMCIy75BEvD9leD8wOqu87PJcuQO9h4EQtntelo480tKv2Oqwa0vREttYE1lHM85ehGeTns+tTe2MnYfvl9NZi5uKiccF16cmbQF4wrVZZ9VS1ryt7MYeYhpWOOcoQlz21AjZewcKoMKBXm9SLtis8WU0ZkO70MaVkvZ0Y54XurIlL+JmWdP38du90iiEwc+M1p44QzZthbgGW01hxBCv0wM92sTrPzMTN8B6HScVupZViqO/m+Zd8NtWPUgoQIsGTNeUtk9oo/iMo/yH0dUz7xqWrozXy6tg+4QCmYgrh67axujUzCmFVMrQIXzv4Cn+Ke8NKY2M4M/jMRZlvlorItDSjiemqflXekt3UnQsYztmCxtIiXIScLVWKQOukFraC3iLwEWWjpQA1xcVseH3xcA2dEEyC4R3xMcHIF288ZQMewBn20wxYdUFNB9w1xZ4HydGMXUnwlxEtr7u2I86SNHqS3M6EC2kxBuHmYL1SyBsWhpn3NjyCouEhXbqsAh/Q2XhBJE0i6lCfz15UPnu9OphFHmw=
    on_start: always
    on_success: always
    on_failure: always
    on_error: always
