version: '3.6'

services:
  drupal-mysql-lib-unb-ca:
    image: mysql:5.7
    restart: always
    command: mysqld --skip-name-resolve --max_allowed_packet=64M
    env_file:
      - ./env/mysql.env
    expose:
     - "3306"
    networks:
      - unbherbarium.lib.unb.ca

  drupal-redis-lib-unb-ca:
    image: redis:5-alpine
    restart: always
    expose:
      - "6379"
    networks:
      - unbherbarium.lib.unb.ca
    env_file:
      - ./env/redis.env

  unbherbarium.lib.unb.ca:
    build:
      context: .
      args:
        - COMPOSER_DEPLOY_DEV=dev
    restart: always
    container_name: unbherbarium.lib.unb.ca
    depends_on:
      - drupal-mysql-lib-unb-ca
    expose:
      - "80"
    networks:
      - unbherbarium.lib.unb.ca
    ports:
      - "3081:80"
    env_file:
      - ./env/drupal.env
    volumes:
      - ./config-yml:/app/configuration
      - ./custom/modules:/app/modules/custom
      - ./custom/themes:/app/themes/custom
      - ./tests:/app/tests

networks:
  unbherbarium.lib.unb.ca:
    name: unbherbarium.lib.unb.ca
