version: '2'

services:
  mysql:
    image: mysql
    command: mysqld --skip-name-resolve
    env_file:
      - ./env/mysql.env
    expose:
     - "3306"

  unbherbarium.ca:
    build:
      context: .
      args:
        - COMPOSER_DEPLOY_DEV=dev
    container_name: unbherbarium.ca
    expose:
     - "80"
    ports:
      - "3081:80"
    env_file:
      - ./env/drupal.env
    volumes:
      - ./config-yml:/app/configuration
      - ./custom/modules:/app/modules/custom
      - ./custom/themes:/app/themes/custom
      - ./tests/behat.yml:/tmp/drupal_build/behat.yml
      - ./tests/features:/tmp/drupal_build/features
