#!/usr/bin/env bash
COMMIT_MSG=`cat $1`
# Validate using node commit-msg
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
${SCRIPTPATH}/../../node_modules/commit-msg/bin/validate "$COMMIT_MSG"
echo $?

regex="^[A-Z]\{2,\}\-[0-9]\+ [^ ].\{15,\}"

echo "here"
msg_test=`grep -e '"$regex"' "$1"`
if [ "$msg_test" == "" ]; then
  echo "Invalid commit message. Include the JIRA project code and issue number. Ensure actual message is at least 15 characters."
  echo "Valid example: PMPOR-135 Add the new picture field to the article feature."
  exit 1;
fi
