#!/usr/bin/env bash

COMMIT_MSG=`cat $1`

# Validate using node commit-msg
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
NODE_LINT_OUTPUT=$( ${SCRIPTPATH}/../../node_modules/commit-msg/bin/validate "$COMMIT_MSG" 2>&1 >/dev/null )
echo "$NODE_LINT_OUTPUT"
if [[ ${NODE_LINT_OUTPUT} == *"error"* ]]; then
  exit 1
fi

# Validate minimum length and JIRA issue.
if [[ ! "$COMMIT_MSG" =~ (^[A-Z]{2,}-[0-9]+ [^ ].{15,}) ]]; then
  echo "Invalid commit message. Include the JIRA project code and issue number. Ensure actual message is at least 15 characters."
  echo "Valid example: PMPOR-135 Add the new picture field to the article feature"
  exit 1
fi
