# The source data is in CSV files, so we use the 'csv' source plugin.
id: cmh_herb_import_standard_HERBIMPORTID
label: Herbarium Sample Import from HERBIMPORTDATE

migration_tags:
  - CSV
  - Herbarium Samples

source:
  plugin: csv
  path: 'HERBIMPORTFILEPATH'
  ids:
    - 'CMH Accession ID'

destination:
  plugin: entity:node

process:
  type:
    plugin: default_value
    default_value: herbarium_specimen

  field_dwc_record_number: 'CMH Accession ID'
  field_taxonomy_tid: 'Species ID'
  field_collector_tid: specimen_collectors
  field_dwc_country_tax: specimen_country
  field_dwc_province_tax: specimen_province
  field_dwc_county_tax: specimen_county
  field_dwc_verbatimlocality: 'Verbatim Locality'
  field_dwc_decimallongitude: 'Longitude'
  field_dwc_decimallatitude: 'Latitude'
  field_dwc_coordinateprecision: geo_precision
  field_geoheritage: geo_heritage
  field_dwc_eventdate: cmh_date
  field_dwc_verbatimeventdate: 'Verbatim Event Date'
  field_dwc_eventremarks: 'Abundance'
  field_dc_contributor_other: 'Data Entry By'
  field_dwc_habitat: 'Habitat'
  field_dwc_occurrenceremarks: 'Occurrence Remarks'
  field_dwc_othercatalognumbers: 'Other Catalogue No.'
  field_previous_identifications: 'Previous Identifications'
  field_dwc_reproductivecondition: 'Reproductive Condition'
