# The source data is in CSV files, so we use the 'csv' source plugin.
id: cmh_herb_import_standard_HERBIMPORTID
label: Herbarium Sample Import from HERBIMPORTDATE

migration_tags:
  - CSV
  - Herbarium Samples

source:
  plugin: csv
  path: 'HERBIMPORTFILEPATH'
  header_row_count: 1
  keys:
    - cmh_accid
  column_names:
    0:
      cmh_accid: CMH Accession ID
    1:
      cmh_specid: Species Taxonomy ID
    2:
      cmh_collectors: Collector(s)
    3:
      cmh_country: Country
    4:
      cmh_province: Province/State
    5:
      cmh_county: County
    6:
      cmh_verbatim_locality: Verbatim Locality
    7:
      cmh_geo_longitude: Longitude
    8:
      cmh_geo_latitude: Latitude
    9:
      cmh_year: Collection Year
    10:
      cmh_month: Collection Month
    11:
      cmh_day: Collection Day
    12:
      cmh_verbatim_date: Verbatim Event Date

destination:
  plugin: entity:node

process:
  type:
    plugin: default_value
    default_value: herbarium_specimen

  field_dwc_record_number: cmh_accid
  field_taxonomy_tid: cmh_specid
  field_collector_tid: specimen_collectors
  field_dwc_country_tax: specimen_country
  field_dwc_province_tax: specimen_province
  field_dwc_county_tax: specimen_county
  field_dwc_verbatimlocality: cmh_verbatim_locality
  field_dwc_decimal_longitude: cmh_geo_longitude
  field_dwc_decimal_latitude: cmh_geo_latitude
  field_dwc_eventdate: cmh_date
  field_dwc_verbatimeventdate: cmh_verbatim_date
