<?php

/**
 * @file
 * Features related to herbarium_specimen_lts.
 */

/**
 * Build batch operations array for specimen surrogates from an archival master.
 *
 * @param object $nid
 *   The node id of the parent herbarium_specimen node.
 * @param object $fid
 *   The file ID of the archival master TIFF File object.
 *
 * @return array
 *   A batch API operations array to generate the required surrogates.
 */
function _herbarium_specimen_lts_store_new_image($nid, $fid) {
  return [
    'title' => t('Updating Archive Image'),
    'init_message' => t('Updating Archive Image'),
    'operations' => [
      [
        [
          'Drupal\herbarium_specimen_lts\HerbariumImageLtsArchiver',
          'archiveFileToLts',
        ],
        [$fid, $nid, \Drupal::currentUser()->id()],
      ],

      [
        [
          'Drupal\herbarium_specimen_lts\HerbariumImageLtsArchiver',
          'cleanupFiles',
        ],
        [$fid, $nid],
      ],
    ],
  ];
}
