<?php

/**
 * @file
 * Features related to herbarium_specimen_lts.
 */

define('HERBARIUM_SPECIMEN_LTS_QUEUE_TABLE', 'herbarium_specimen_lts_lts_image_queue');
define('HERBARIUM_SPECIMEN_LTS_QUEUE_STATUS_UNPROCESSED', 0);
define('HERBARIUM_SPECIMEN_LTS_QUEUE_STATUS_PROCESSING', 1);
define('HERBARIUM_SPECIMEN_LTS_QUEUE_STATUS_FAIL_NO_NODE_ACCID', 2);
define('HERBARIUM_SPECIMEN_LTS_QUEUE_STATUS_FAIL_NO_SURROGATES', 3);
define('HERBARIUM_SPECIMEN_LTS_QUEUE_STATUS_FAIL_NO_DZI', 4);
define('HERBARIUM_SPECIMEN_LTS_QUEUE_STATUS_FAIL_NOT_ARCHIVED', 5);
define('HERBARIUM_SPECIMEN_LTS_QUEUE_STATUS_COMPLETE', 10);

/**
 * Build batch operations array for specimen surrogates from an archival master.
 *
 * @param object $nid
 *   The node id of the parent herbarium_specimen node.
 * @param object $file_path
 *   The file path of the archival master TIFF File object.
 *
 * @return array
 *   A batch API operations array to generate the required surrogates.
 */
function _herbarium_specimen_lts_store_new_image($nid, $file_path) {
  return [
    'title' => t('Updating Archive Image'),
    'init_message' => t('Updating Archive Image'),
    'operations' => [
      [
        [
          'Drupal\herbarium_specimen_lts\HerbariumImageLtsArchiver',
          'archiveFileToLts',
        ],
        [$nid, $file_path, \Drupal::currentUser()->id()],

      ],
      [
        [
          'Drupal\herbarium_specimen_lts\HerbariumImageLtsArchiver',
          'auditDrushBatch',
        ],
        [$nid, $file_path],
      ],
    ],
  ];
}

function _herbarium_specimen_lts_set_file_status($file_path, $status) {
  $sql = 'UPDATE ' . HERBARIUM_SPECIMEN_LTS_QUEUE_TABLE . " SET status=$status WHERE file='$file_path'";
  return db_query($sql);
}
