<?php

/**
 * @file
 * Contains herbarium_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function herbarium_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the herbarium_core module.
    case 'help.page.herbarium_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Herbarium Core Functions') . '</p>';
      return $output;

    default:
  }
}

/**
 * Returns the parent id of a given taxonomy term id.
 */
function _herbarium_core_get_specimen_parent($tid) {
  $storage = \Drupal::service('entity_type.manager')->getStorage('taxonomy_term');
  $parent_object_array = $storage->loadParents($tid);
  return array_shift(
    array_keys($parent_object_array)
  );
}
