<?php

/**
 * @file
 * Contains herbarium_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
define('HERBARIUM_CORE_SPECIMEN_VOCABULARY_ID', 'herbarium_specimen_taxonomy');

/**
 * Implements hook_help().
 */
function herbarium_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the herbarium_core module.
    case 'help.page.herbarium_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Herbarium Core Functions') . '</p>';
      return $output;

    default:
  }
}

/**
 * Returns the parent id of a given taxonomy term id.
 */
function _herbarium_core_get_specimen_parent($tid) {
/**
 * Returns the first parent of a given taxonomy term.
 *
 * @param int $tid
 *   The term ID of the term to query.
 *
 * @return int
 *   The term ID of the parent term, FALSE if term has no parents.
 */
function _herbarium_core_get_term_first_parent($tid) {
  $storage = \Drupal::service('entity_type.manager')->getStorage('taxonomy_term');
  /* @var $storage \Drupal\taxonomy\TermStorageInterface */

  $parent_object_array = $storage->loadParents($tid);
  if (!empty($parent_object_array)) {
    return array_shift($parent_object_array)->id();
  }
  return FALSE;
}
