spt_table:
  -
    status: '1'
    pages: "/manage/*\r\n/user/login\r\n/collectorlist/*\r\n/countrylist/*\r\n/countylist/*\r\n/provincelist/*"
    theme_key: ''
    theme: unbherbarium_admin_theme
    weight: '-10'
    roles:
      anonymous: '0'
      authenticated: '0'
      administrator: '0'
      researcher: '0'
      cmh_database_administrator: '0'
      editor: '0'
    language:
      en: 0
