_core:
  default_config_hash: bRFagEWOnJOtglJnv0ALb3R7xf4n9wT7J4-1AJ8RNnc
favicon:
  mimetype: image/svg+xml
  path: themes/custom/0_unbherbarium_ca/dist/img/favicon.svg
  url: 'http://unbherbarium.lib.unb.ca/themes/custom/0_unbherbarium_ca/favicon.ico'
  use_default: 0
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: 0
bootstrap_source: '0'
bootstrap_container: container
bootstrap_region_clean_header: 1
bootstrap_region_class_header: ''
bootstrap_region_clean_page_top: 0
bootstrap_region_class_page_top: row
bootstrap_region_clean_page_bottom: 0
bootstrap_region_class_page_bottom: row
bootstrap_region_clean_highlighted: 1
bootstrap_region_class_highlighted: ''
bootstrap_region_clean_content: 1
bootstrap_region_class_content: ''
bootstrap_region_clean_sidebar_first: 1
bootstrap_region_class_sidebar_first: ''
bootstrap_region_clean_sidebar_second: 1
bootstrap_region_class_sidebar_second: ''
bootstrap_sidebar_position: left
bootstrap_content_offset: 0
bootstrap_sidebar_collapse: 0
bootstrap_sidebar_first_width: 2
bootstrap_sidebar_first_offset: 0
bootstrap_sidebar_second_width: 2
bootstrap_sidebar_second_offset: 0
bootstrap_hide_node_label: 0
bootstrap_breadcrumb_divider: ''
bootstrap_button: 0
bootstrap_button_size: ''
bootstrap_button_type: primary
bootstrap_button_outline: 0
bootstrap_navbar_container: '0'
bootstrap_navbar_toggle: navbar-toggleable-xl
bootstrap_navbar_top_navbar: 0
bootstrap_navbar_top_class: ''
bootstrap_navbar_class: ''
bootstrap_navbar_top_position: ''
bootstrap_navbar_top_color: ''
bootstrap_navbar_top_background: ''
bootstrap_navbar_position: ''
bootstrap_navbar_color: ''
bootstrap_navbar_background: ''
bootstrap_navbar_flyout: false
bootstrap_navbar_slide: false
bootstrap_navbar_offcanvas: ''
bootstrap_messages_widget: default
bootstrap_messages_widget_toast_delay: 10000
bootstrap_float_label: '0'
bootstrap_checkbox: ''
bootstrap_navbar_top_affix: 0
bootstrap_navbar_affix: 0
bootstrap_sidebar_first_affix: 0
bootstrap_sidebar_second_affix: 0
bootstrap_scroll_spy: ''
bootstrap_google_fonts: ''
bootstrap_bootstrap_icons: 0
bootstrap_icons: ''
bootstrap_system_messages: ''
bootstrap_table_style: ''
bootstrap_table_hover: 0
bootstrap_table_head: ''
bootstrap_image_fluid: false
bootstrap_tabs_style: ''
bootstrap_enable_color: false
cdn_provider: ''
navbar_position: fixed-top
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
table_responsive: '-1'
table: ''
navbar_inverse: 1
breadcrumb: '0'
modal_enabled: 0
schemas:
  bootstrap: 8000
  unbherbarium_ca: 8000
tooltip_placement: 'auto bottom'
tooltip_trigger: focus
cdn_theme: ''
cdn_cache_ttl_versions: 0
cdn_cache_ttl_themes: 0
cdn_cache_ttl_assets: 0
cdn_cache_ttl_library: 0
reset_http_request_cache: ''
bootstrap_region_clean_navigation: 0
bootstrap_region_width_navigation: 0
bootstrap_region_class_navigation: row
bootstrap_region_clean_navigation_collapsible: 0
bootstrap_region_width_navigation_collapsible: 0
bootstrap_region_class_navigation_collapsible: row
bootstrap_region_width_header: 0
bootstrap_region_width_highlighted: 0
bootstrap_region_clean_help: 0
bootstrap_region_width_help: 0
bootstrap_region_class_help: row
bootstrap_region_width_content: 0
bootstrap_region_width_sidebar_first: 0
bootstrap_region_width_sidebar_second: 0
bootstrap_region_clean_footer: 0
bootstrap_region_width_footer: 0
bootstrap_region_class_footer: row
bootstrap_region_width_page_top: 0
bootstrap_region_width_page_bottom: 0
