minimum_single: 10
minimum_multiple: 20
disable_search_threshold: 0
minimum_width: 256
jquery_selector: 'select[name="collector"],select[name="field_taxonomy_tid"]'
search_contains: true
disable_search: false
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
disabled_themes:
  bartik: '0'
  seven: '0'
  bootstrap: '0'
  unbherbarium_ca: '0'
chosen_include: 2
_core:
  default_config_hash: m09-D9lEMh3sNiyny5OkBaqyKB7-A-zhUsFZ2Rbq7nQ
