last_optimize: 0
autocomplete_max_occurrences: 0.9
index_prefix: ''
http_get_max_length: 4000
cron_action: spellcheck
site_hash: dmcv50
_core:
  default_config_hash: ov-h0wJCsQh751aM0x1Pz93pw7GlK20OX2pNTNqBLnE
