cdn_provider: ''
logo:
  path: ''
  url: ''
  use_default: 0
navbar_position: fixed-top
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
table_responsive: '-1'
table: ''
navbar_inverse: 1
breadcrumb: '0'
favicon:
  mimetype: image/png
  path: ''
  url: 'http://unbherbarium.lib.unb.ca/themes/custom/0_unbherbarium_ca/favicon.ico'
  use_default: 1
_core:
  default_config_hash: bRFagEWOnJOtglJnv0ALb3R7xf4n9wT7J4-1AJ8RNnc
schemas:
  bootstrap: 8000
  unbherbarium_ca: 8000
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 0
  node_user_picture: 1
modal_enabled: 0
